### ISSUE TITLE
Auto-formatter for the code

### ISSUE THREAD

**Issue by ajshajib** [LSST-strong-lensing/sim-pipeline#40]
I think it would be helpful to add code autoformatters: `black` and `docformatter` using pre-commit, as was recently done for the software `lenstronomy`. This feature would make automatic commits to fix code-formatting issues for each PR. The maximum line-length will then be set at 88 characters.

If that sounds ok, I can work on it after the `gg-lensing` is merged into the `main` branch.

**Comment by sibirrer** [comment]
That would be great @ajshajib ! Yes, let's wait for the first merge of gg_lensing branch such that the main branch has something to offer :)
